# Generated by Django 4.1.4 on 2023-05-24 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Donor", "Donor"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        default="Donor",
                        max_length=100,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O +ve", "O +ve"),
                            ("O -ve", "O -ve"),
                            ("A +ve", "A +ve"),
                            ("A -ve", "A -ve"),
                            ("B +ve", "B +ve"),
                            ("B -ve", "B -ve"),
                            ("AB +ve", "AB +ve"),
                            ("AB -ve", "AB -ve"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "house_no",
                    models.CharField(
                        help_text="House No/House Name/Street Name",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh ", "Arunachal Pradesh "),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir ", "Jammu and Kashmir "),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Chandigarh", "Chandigarh"),
                            ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli"),
                            ("Daman and Diu", "Daman and Diu"),
                            ("Lakshadweep", "Lakshadweep"),
                            (
                                "National Capital Territory of Delhi",
                                "National Capital Territory of Delhi",
                            ),
                            ("Puducherry", "Puducherry"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        max_length=500,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[1-9]{1}[0-9]{2}\\s{0,1}[0-9]{3}$",
                                message="Enter a Valid PIN Code",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "compatible_types",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A +ve,AB +ve", "A +ve,AB +ve"),
                            ("O +ve,A +ve,;B +ve,AB +ve", "O +ve,A +ve,B +ve,AB +ve"),
                            (";B +ve,AB +ve", "B +ve,AB +ve"),
                            ("AB +ve", "AB +ve"),
                            ("A +ve,A -ve,AB -ve,AB +ve", "A +ve,A -ve,AB -ve,AB +ve"),
                            (
                                "A +ve,A -ve,O -ve,O +ve,AB +ve,AB -ve,;B +ve,;B -ve",
                                "A +ve,A -ve,O -ve,O +ve,AB +ve,AB -ve,B +ve,B -ve",
                            ),
                            (
                                ";B +ve,;B -ve,AB -ve,AB +ve",
                                "B +ve,B -ve,AB -ve,AB +ve",
                            ),
                            ("AB +ve,AB -ve", "AB +ve,AB -ve"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("required_by", models.DateField()),
                (
                    "location",
                    models.CharField(help_text="Hospital Location", max_length=300),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O +ve", "O +ve"),
                            ("O -ve", "O -ve"),
                            ("A +ve", "A +ve"),
                            ("A -ve", "A -ve"),
                            ("B +ve", "B +ve"),
                            ("B -ve", "B -ve"),
                            ("AB +ve", "AB +ve"),
                            ("AB -ve", "AB -ve"),
                        ],
                        max_length=100,
                    ),
                ),
                ("include_compatible_blood", models.BooleanField(default=False)),
                (
                    "requirements",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "request_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.donor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("date_approved", models.DateTimeField()),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.donor"
                    ),
                ),
                (
                    "donor_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.donorrequest",
                    ),
                ),
            ],
        ),
    ]
