# Generated by Django 4.1.4 on 2022-12-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O +ve", "O +ve"),
                            ("O -ve", "O -ve"),
                            ("A +ve", "A +ve"),
                            ("A -ve", "A -ve"),
                            ("B +ve", "B +ve"),
                            ("B -ve", "B -ve"),
                            ("AB +ve", "AB +ve"),
                            ("AB -ve", "AB -ve"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.TextField(max_length=300)),
                ("last_donated", models.DateField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
