# Generated by Django 4.1.4 on 2023-01-06 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Donor", "Donor"),
                            ("Unauthorized", "Unauthorized"),
                        ],
                        default="Donor",
                        max_length=100,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("O +ve", "O +ve"),
                            ("O -ve", "O -ve"),
                            ("A +ve", "A +ve"),
                            ("A -ve", "A -ve"),
                            ("B +ve", "B +ve"),
                            ("B -ve", "B -ve"),
                            ("AB +ve", "AB +ve"),
                            ("AB -ve", "AB -ve"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.TextField(max_length=300)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "compatible_typrs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A +ve", "A +ve,AB +ve"),
                            ("O +ve", "O +ve,A +ve,B +ve,AB +ve"),
                            ("B +ve", "B +ve,AB +ve"),
                            ("AB +ve", "AB +ve"),
                            ("A -ve", "A +ve,A -ve,AB -ve,AB +ve"),
                            (
                                "O -ve",
                                "A +ve,A -ve,O -ve,O +ve,AB +ve,AB -ve,B +ve,B -ve",
                            ),
                            ("B -ve", "B +ve,B -ve,AB -ve,AB +ve"),
                            ("AB -ve", "AB +ve,AB -ve"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
