# Generated by Django 4.1.4 on 2023-05-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorapproval',
            old_name='donor',
            new_name='accepting_donor',
        ),
    ]
