# Generated by Django 4.1.4 on 2022-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
