# Generated by Django 4.1.4 on 2023-01-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="compatible_typrs",
            new_name="compatible_types",
        ),
    ]
