# Generated by Django 4.1.4 on 2022-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_donor_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
