# Generated by Django 4.1.4 on 2023-01-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_compatible_typrs_donor_compatible_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="compatible_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A +ve,AB +ve", "A +ve,AB +ve"),
                    ("O +ve,A +ve,B +ve,AB +ve", "O +ve,A +ve,B +ve,AB +ve"),
                    ("B +ve,AB +ve", "B +ve,AB +ve"),
                    ("AB +ve", "AB +ve"),
                    ("A +ve,A -ve,AB -ve,AB +ve", "A +ve,A -ve,AB -ve,AB +ve"),
                    (
                        "A +ve,A -ve,O -ve,O +ve,AB +ve,AB -ve,B +ve,B -ve",
                        "A +ve,A -ve,O -ve,O +ve,AB +ve,AB -ve,B +ve,B -ve",
                    ),
                    ("B +ve,B -ve,AB -ve,AB +ve", "B +ve,B -ve,AB -ve,AB +ve"),
                    ("AB +ve,AB -ve", "AB +ve,AB -ve"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
