# Generated by Django 4.1.4 on 2023-05-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_donor_address_donor_house_no_donor_pin_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(help_text='Hospital Location', max_length=300)),
                ('blood_type', models.CharField(choices=[('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve')], max_length=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donation_status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('donor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.donorrequest')),
            ],
        ),
    ]
