# Generated by Django 4.1.4 on 2023-05-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_donor_donorapproval_accepting_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorapproval',
            old_name='accepting_donor',
            new_name='donor',
        ),
    ]
