# Generated by Django 4.1.4 on 2022-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_donor_last_donated"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Donor", "Donor")],
                default="Donor",
                max_length=100,
            ),
        ),
    ]
