# Generated by Django 4.1.4 on 2023-05-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_accepting_donor_donorapproval_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
