# Generated by Django 4.1.4 on 2023-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_donorrequest_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorapproval',
            old_name='donor',
            new_name='donor_a',
        ),
        migrations.RenameField(
            model_name='donorrequest',
            old_name='donor',
            new_name='donor_r',
        ),
        migrations.AlterField(
            model_name='donorapproval',
            name='donation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
