# Generated by Django 4.1.4 on 2023-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_donorrequest_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
    ]
