# Generated by Django 4.1.4 on 2023-05-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_donor_donorapproval_donor_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorrequest',
            old_name='donor_r',
            new_name='donor',
        ),
    ]
