# Generated by Django 4.1.4 on 2023-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_donorrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
