# Generated by Django 4.1.4 on 2023-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_donorrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='requirements',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
