# Generated by Django 4.1.4 on 2023-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_donorrequest_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='include_compatible_blood',
            field=models.BooleanField(default=False),
        ),
    ]
