# Generated by Django 4.1.4 on 2023-05-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_donorrequest_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorrequest',
            name='date_of_birth',
        ),
    ]
